#!/bin/sh
PORT=$1
if [ "$PORT" = "" ]; then
  PORT=6379
fi

redis-cli -p $PORT hmset "kanacell:あ" "kana" "あ"
redis-cli -p $PORT hmset "kanacell:い" "kana" "い"
redis-cli -p $PORT hmset "kanacell:う" "kana" "う"
redis-cli -p $PORT hmset "kanacell:え" "kana" "え"
redis-cli -p $PORT hmset "kanacell:お" "kana" "お"

redis-cli -p $PORT hmset "kanacell:か" "kana" "か"
redis-cli -p $PORT hmset "kanacell:き" "kana" "き"
redis-cli -p $PORT hmset "kanacell:く" "kana" "く"
redis-cli -p $PORT hmset "kanacell:け" "kana" "け"
redis-cli -p $PORT hmset "kanacell:こ" "kana" "こ"

redis-cli -p $PORT hmset "kanacell:さ" "kana" "さ"
redis-cli -p $PORT hmset "kanacell:し" "kana" "し"
redis-cli -p $PORT hmset "kanacell:す" "kana" "す"
redis-cli -p $PORT hmset "kanacell:せ" "kana" "せ"
redis-cli -p $PORT hmset "kanacell:そ" "kana" "そ"

redis-cli -p $PORT hmset "kanacell:た" "kana" "た"
redis-cli -p $PORT hmset "kanacell:ち" "kana" "ち"
redis-cli -p $PORT hmset "kanacell:つ" "kana" "つ"
redis-cli -p $PORT hmset "kanacell:て" "kana" "て"
redis-cli -p $PORT hmset "kanacell:と" "kana" "と"

redis-cli -p $PORT hmset "kanacell:な" "kana" "な"
redis-cli -p $PORT hmset "kanacell:に" "kana" "に"
redis-cli -p $PORT hmset "kanacell:ぬ" "kana" "ぬ"
redis-cli -p $PORT hmset "kanacell:ね" "kana" "ね"
redis-cli -p $PORT hmset "kanacell:の" "kana" "の"

redis-cli -p $PORT hmset "kanacell:は" "kana" "は"
redis-cli -p $PORT hmset "kanacell:ひ" "kana" "ひ"
redis-cli -p $PORT hmset "kanacell:ふ" "kana" "ふ"
redis-cli -p $PORT hmset "kanacell:へ" "kana" "へ"
redis-cli -p $PORT hmset "kanacell:ほ" "kana" "ほ"

redis-cli -p $PORT hmset "kanacell:ま" "kana" "ま"
redis-cli -p $PORT hmset "kanacell:み" "kana" "み"
redis-cli -p $PORT hmset "kanacell:む" "kana" "む"
redis-cli -p $PORT hmset "kanacell:め" "kana" "め"
redis-cli -p $PORT hmset "kanacell:も" "kana" "も"

redis-cli -p $PORT hmset "kanacell:や" "kana" "や"
redis-cli -p $PORT hmset "kanacell:ゆ" "kana" "ゆ"
redis-cli -p $PORT hmset "kanacell:よ" "kana" "よ"

redis-cli -p $PORT hmset "kanacell:ら" "kana" "ら"
redis-cli -p $PORT hmset "kanacell:り" "kana" "り"
redis-cli -p $PORT hmset "kanacell:る" "kana" "る"
redis-cli -p $PORT hmset "kanacell:れ" "kana" "れ"
redis-cli -p $PORT hmset "kanacell:ろ" "kana" "ろ"

redis-cli -p $PORT hmset "kanacell:わ" "kana" "わ"
redis-cli -p $PORT hmset "kanacell:を" "kana" "を"
redis-cli -p $PORT hmset "kanacell:を" "kana" "を"
redis-cli -p $PORT hmset "kanacell:ん" "kana" "ん"

redis-cli -p $PORT hmset "kanacell:が" "kana" "が"
redis-cli -p $PORT hmset "kanacell:ぎ" "kana" "ぎ"
redis-cli -p $PORT hmset "kanacell:ぐ" "kana" "ぐ"
redis-cli -p $PORT hmset "kanacell:げ" "kana" "げ"
redis-cli -p $PORT hmset "kanacell:ご" "kana" "ご"

redis-cli -p $PORT hmset "kanacell:ざ" "kana" "ざ"
redis-cli -p $PORT hmset "kanacell:じ" "kana" "じ"
redis-cli -p $PORT hmset "kanacell:ず" "kana" "ず"
redis-cli -p $PORT hmset "kanacell:ぜ" "kana" "ぜ"
redis-cli -p $PORT hmset "kanacell:ぞ" "kana" "ぞ"

redis-cli -p $PORT hmset "kanacell:だ" "kana" "だ"
redis-cli -p $PORT hmset "kanacell:じ" "kana" "じ"
redis-cli -p $PORT hmset "kanacell:ず" "kana" "ず"
redis-cli -p $PORT hmset "kanacell:で" "kana" "で"
redis-cli -p $PORT hmset "kanacell:ど" "kana" "ど"

redis-cli -p $PORT hmset "kanacell:ば" "kana" "ば"
redis-cli -p $PORT hmset "kanacell:び" "kana" "び"
redis-cli -p $PORT hmset "kanacell:ぶ" "kana" "ぶ"
redis-cli -p $PORT hmset "kanacell:べ" "kana" "べ"
redis-cli -p $PORT hmset "kanacell:ぼ" "kana" "ぼ"

redis-cli -p $PORT hmset "kanacell:ぱ" "kana" "ぱ"
redis-cli -p $PORT hmset "kanacell:ぴ" "kana" "ぴ"
redis-cli -p $PORT hmset "kanacell:ぷ" "kana" "ぷ"
redis-cli -p $PORT hmset "kanacell:ぺ" "kana" "ぺ"
redis-cli -p $PORT hmset "kanacell:ぽ" "kana" "ぽ"

redis-cli -p $PORT hmset "kanacell:きゃ" "kana" "きゃ"
redis-cli -p $PORT hmset "kanacell:きゅ" "kana" "きゅ"
redis-cli -p $PORT hmset "kanacell:きょ" "kana" "きょ"
redis-cli -p $PORT hmset "kanacell:しゃ" "kana" "しゃ"
redis-cli -p $PORT hmset "kanacell:しゅ" "kana" "しゅ"
redis-cli -p $PORT hmset "kanacell:しょ" "kana" "しょ"
redis-cli -p $PORT hmset "kanacell:ちゃ" "kana" "ちゃ"
redis-cli -p $PORT hmset "kanacell:ちゅ" "kana" "ちゅ"
redis-cli -p $PORT hmset "kanacell:ちょ" "kana" "ちょ"
redis-cli -p $PORT hmset "kanacell:にゃ" "kana" "にゃ"
redis-cli -p $PORT hmset "kanacell:にゅ" "kana" "にゅ"
redis-cli -p $PORT hmset "kanacell:にょ" "kana" "にょ"
redis-cli -p $PORT hmset "kanacell:ひゃ" "kana" "ひゃ"
redis-cli -p $PORT hmset "kanacell:ひゅ" "kana" "ひゅ"
redis-cli -p $PORT hmset "kanacell:ひょ" "kana" "ひょ"
redis-cli -p $PORT hmset "kanacell:みゃ" "kana" "みゃ"
redis-cli -p $PORT hmset "kanacell:みゅ" "kana" "みゅ"
redis-cli -p $PORT hmset "kanacell:みょ" "kana" "みょ"
redis-cli -p $PORT hmset "kanacell:りゃ" "kana" "りゃ"
redis-cli -p $PORT hmset "kanacell:りゅ" "kana" "りゅ"
redis-cli -p $PORT hmset "kanacell:りょ" "kana" "りょ"
redis-cli -p $PORT hmset "kanacell:ぎゃ" "kana" "ぎゃ"
redis-cli -p $PORT hmset "kanacell:ぎゅ" "kana" "ぎゅ"
redis-cli -p $PORT hmset "kanacell:ぎょ" "kana" "ぎょ"
redis-cli -p $PORT hmset "kanacell:じゃ" "kana" "じゃ"
redis-cli -p $PORT hmset "kanacell:じゃ" "kana" "じゃ"
redis-cli -p $PORT hmset "kanacell:じゅ" "kana" "じゅ"
redis-cli -p $PORT hmset "kanacell:じゅ" "kana" "じゅ"
redis-cli -p $PORT hmset "kanacell:じょ" "kana" "じょ"
redis-cli -p $PORT hmset "kanacell:じょ" "kana" "じょ"
redis-cli -p $PORT hmset "kanacell:びゃ" "kana" "びゃ"
redis-cli -p $PORT hmset "kanacell:びゅ" "kana" "びゅ"
redis-cli -p $PORT hmset "kanacell:びょ" "kana" "びょ"
redis-cli -p $PORT hmset "kanacell:ぴゃ" "kana" "ぴゃ"
redis-cli -p $PORT hmset "kanacell:ぴゅ" "kana" "ぴゅ"
redis-cli -p $PORT hmset "kanacell:ぴょ" "kana" "ぴょ"
