#!/bin/sh
PORT=$1
if [ "$PORT" = "" ]; then
  PORT=6379
fi

redis-cli -p $PORT hmset "map2:hiragana" "_a" "あ"
redis-cli -p $PORT hmset "map2:hiragana" "_i" "い"
redis-cli -p $PORT hmset "map2:hiragana" "_u" "う"
redis-cli -p $PORT hmset "map2:hiragana" "_e" "え"
redis-cli -p $PORT hmset "map2:hiragana" "_o" "お"

redis-cli -p $PORT hmset "map2:hiragana" "a"  "あ"
redis-cli -p $PORT hmset "map2:hiragana" "i"  "い"
redis-cli -p $PORT hmset "map2:hiragana" "u"  "う"
redis-cli -p $PORT hmset "map2:hiragana" "e"  "え"
redis-cli -p $PORT hmset "map2:hiragana" "o"  "お"

redis-cli -p $PORT hmset "map2:hiragana" "ka" "か"
redis-cli -p $PORT hmset "map2:hiragana" "ki" "き"
redis-cli -p $PORT hmset "map2:hiragana" "ku" "く"
redis-cli -p $PORT hmset "map2:hiragana" "ke" "け"
redis-cli -p $PORT hmset "map2:hiragana" "ko" "こ"

redis-cli -p $PORT hmset "map2:hiragana" "sa" "さ"
redis-cli -p $PORT hmset "map2:hiragana" "si" "し"
redis-cli -p $PORT hmset "map2:hiragana" "su" "す"
redis-cli -p $PORT hmset "map2:hiragana" "se" "せ"
redis-cli -p $PORT hmset "map2:hiragana" "so" "そ"

redis-cli -p $PORT hmset "map2:hiragana" "ta" "た"
redis-cli -p $PORT hmset "map2:hiragana" "ti" "ち"
redis-cli -p $PORT hmset "map2:hiragana" "tu" "つ"
redis-cli -p $PORT hmset "map2:hiragana" "te" "て"
redis-cli -p $PORT hmset "map2:hiragana" "to" "と"

redis-cli -p $PORT hmset "map2:hiragana" "na" "な"
redis-cli -p $PORT hmset "map2:hiragana" "ni" "に"
redis-cli -p $PORT hmset "map2:hiragana" "nu" "ぬ"
redis-cli -p $PORT hmset "map2:hiragana" "ne" "ね"
redis-cli -p $PORT hmset "map2:hiragana" "no" "の"

redis-cli -p $PORT hmset "map2:hiragana" "ha" "は"
redis-cli -p $PORT hmset "map2:hiragana" "hi" "ひ"
redis-cli -p $PORT hmset "map2:hiragana" "hu" "ふ"
redis-cli -p $PORT hmset "map2:hiragana" "he" "へ"
redis-cli -p $PORT hmset "map2:hiragana" "ho" "ほ"

redis-cli -p $PORT hmset "map2:hiragana" "ma" "ま"
redis-cli -p $PORT hmset "map2:hiragana" "mi" "み"
redis-cli -p $PORT hmset "map2:hiragana" "mu" "む"
redis-cli -p $PORT hmset "map2:hiragana" "me" "め"
redis-cli -p $PORT hmset "map2:hiragana" "mo" "も"

redis-cli -p $PORT hmset "map2:hiragana" "ya" "や"
redis-cli -p $PORT hmset "map2:hiragana" "yu" "ゆ"
redis-cli -p $PORT hmset "map2:hiragana" "yo" "よ"

redis-cli -p $PORT hmset "map2:hiragana" "ra" "ら"
redis-cli -p $PORT hmset "map2:hiragana" "ri" "り"
redis-cli -p $PORT hmset "map2:hiragana" "ru" "る"
redis-cli -p $PORT hmset "map2:hiragana" "re" "れ"
redis-cli -p $PORT hmset "map2:hiragana" "ro" "ろ"

redis-cli -p $PORT hmset "map2:hiragana" "wa" "わ"
redis-cli -p $PORT hmset "map2:hiragana" "wo" "を"
redis-cli -p $PORT hmset "map2:hiragana" "n" "ん"

redis-cli -p $PORT hmset "map2:hiragana" "ga" "が"
redis-cli -p $PORT hmset "map2:hiragana" "gi" "ぎ"
redis-cli -p $PORT hmset "map2:hiragana" "gu" "ぐ"
redis-cli -p $PORT hmset "map2:hiragana" "ge" "げ"
redis-cli -p $PORT hmset "map2:hiragana" "go" "ご"

redis-cli -p $PORT hmset "map2:hiragana" "za" "ざ"
redis-cli -p $PORT hmset "map2:hiragana" "zi" "じ"
redis-cli -p $PORT hmset "map2:hiragana" "zu" "ず"
redis-cli -p $PORT hmset "map2:hiragana" "ze" "ぜ"
redis-cli -p $PORT hmset "map2:hiragana" "zo" "ぞ"

redis-cli -p $PORT hmset "map2:hiragana" "da" "だ"
redis-cli -p $PORT hmset "map2:hiragana" "di" "じ"
redis-cli -p $PORT hmset "map2:hiragana" "du" "ず"
redis-cli -p $PORT hmset "map2:hiragana" "de" "で"
redis-cli -p $PORT hmset "map2:hiragana" "do" "ど"

redis-cli -p $PORT hmset "map2:hiragana" "ba" "ば"
redis-cli -p $PORT hmset "map2:hiragana" "bi" "び"
redis-cli -p $PORT hmset "map2:hiragana" "bu" "ぶ"
redis-cli -p $PORT hmset "map2:hiragana" "be" "べ"
redis-cli -p $PORT hmset "map2:hiragana" "bo" "ぼ"

redis-cli -p $PORT hmset "map2:hiragana" "pa" "ぱ"
redis-cli -p $PORT hmset "map2:hiragana" "pi" "ぴ"
redis-cli -p $PORT hmset "map2:hiragana" "pu" "ぷ"
redis-cli -p $PORT hmset "map2:hiragana" "pe" "ぺ"
redis-cli -p $PORT hmset "map2:hiragana" "po" "ぽ"

redis-cli -p $PORT hmset "map2:hiragana" "kya" "きゃ"
redis-cli -p $PORT hmset "map2:hiragana" "kyu" "きゅ"
redis-cli -p $PORT hmset "map2:hiragana" "kyo" "きょ"
redis-cli -p $PORT hmset "map2:hiragana" "sya" "しゃ"
redis-cli -p $PORT hmset "map2:hiragana" "syu" "しゅ"
redis-cli -p $PORT hmset "map2:hiragana" "syo" "しょ"
redis-cli -p $PORT hmset "map2:hiragana" "tya" "ちゃ"
redis-cli -p $PORT hmset "map2:hiragana" "tyu" "ちゅ"
redis-cli -p $PORT hmset "map2:hiragana" "tyo" "ちょ"
redis-cli -p $PORT hmset "map2:hiragana" "nya" "にゃ"
redis-cli -p $PORT hmset "map2:hiragana" "nyu" "にゅ"
redis-cli -p $PORT hmset "map2:hiragana" "nyo" "にょ"
redis-cli -p $PORT hmset "map2:hiragana" "hya" "ひゃ"
redis-cli -p $PORT hmset "map2:hiragana" "hyu" "ひゅ"
redis-cli -p $PORT hmset "map2:hiragana" "hyo" "ひょ"
redis-cli -p $PORT hmset "map2:hiragana" "mya" "みゃ"
redis-cli -p $PORT hmset "map2:hiragana" "myu" "みゅ"
redis-cli -p $PORT hmset "map2:hiragana" "myo" "みょ"
redis-cli -p $PORT hmset "map2:hiragana" "rya" "りゃ"
redis-cli -p $PORT hmset "map2:hiragana" "ryu" "りゅ"
redis-cli -p $PORT hmset "map2:hiragana" "ryo" "りょ"
redis-cli -p $PORT hmset "map2:hiragana" "gya" "ぎゃ"
redis-cli -p $PORT hmset "map2:hiragana" "gyu" "ぎゅ"
redis-cli -p $PORT hmset "map2:hiragana" "gyo" "ぎょ"
redis-cli -p $PORT hmset "map2:hiragana" "zya" "じゃ"
redis-cli -p $PORT hmset "map2:hiragana" "zyu" "じゅ"
redis-cli -p $PORT hmset "map2:hiragana" "zyo" "じょ"
redis-cli -p $PORT hmset "map2:hiragana" "bya" "びゃ"
redis-cli -p $PORT hmset "map2:hiragana" "byu" "びゅ"
redis-cli -p $PORT hmset "map2:hiragana" "byo" "びょ"
redis-cli -p $PORT hmset "map2:hiragana" "pya" "ぴゃ"
redis-cli -p $PORT hmset "map2:hiragana" "pyu" "ぴゅ"
redis-cli -p $PORT hmset "map2:hiragana" "pyo" "ぴょ"
