#!/bin/sh
PORT=$1
if [ "$PORT" = "" ]; then
  PORT=6379
fi

redis-cli -p $PORT hmset "map2:katakana" "_a" "ア"
redis-cli -p $PORT hmset "map2:katakana" "_i" "イ"
redis-cli -p $PORT hmset "map2:katakana" "_u" "ウ"
redis-cli -p $PORT hmset "map2:katakana" "_e" "エ"
redis-cli -p $PORT hmset "map2:katakana" "_o" "オ"

redis-cli -p $PORT hmset "map2:katakana" "a"  "ア"
redis-cli -p $PORT hmset "map2:katakana" "i"  "イ"
redis-cli -p $PORT hmset "map2:katakana" "u"  "ウ"
redis-cli -p $PORT hmset "map2:katakana" "e"  "エ"
redis-cli -p $PORT hmset "map2:katakana" "o"  "オ"

redis-cli -p $PORT hmset "map2:katakana" "ka" "カ"
redis-cli -p $PORT hmset "map2:katakana" "ki" "キ"
redis-cli -p $PORT hmset "map2:katakana" "ku" "ク"
redis-cli -p $PORT hmset "map2:katakana" "ke" "ケ"
redis-cli -p $PORT hmset "map2:katakana" "ko" "コ"

redis-cli -p $PORT hmset "map2:katakana" "sa" "サ"
redis-cli -p $PORT hmset "map2:katakana" "si" "シ"
redis-cli -p $PORT hmset "map2:katakana" "su" "ス"
redis-cli -p $PORT hmset "map2:katakana" "se" "セ"
redis-cli -p $PORT hmset "map2:katakana" "so" "ソ"

redis-cli -p $PORT hmset "map2:katakana" "ta" "タ"
redis-cli -p $PORT hmset "map2:katakana" "ti" "チ"
redis-cli -p $PORT hmset "map2:katakana" "tu" "ツ"
redis-cli -p $PORT hmset "map2:katakana" "te" "テ"
redis-cli -p $PORT hmset "map2:katakana" "to" "ト"

redis-cli -p $PORT hmset "map2:katakana" "na" "ナ"
redis-cli -p $PORT hmset "map2:katakana" "ni" "ニ"
redis-cli -p $PORT hmset "map2:katakana" "nu" "ヌ"
redis-cli -p $PORT hmset "map2:katakana" "ne" "ネ"
redis-cli -p $PORT hmset "map2:katakana" "no" "ノ"

redis-cli -p $PORT hmset "map2:katakana" "ha" "ハ"
redis-cli -p $PORT hmset "map2:katakana" "hi" "ヒ"
redis-cli -p $PORT hmset "map2:katakana" "hu" "フ"
redis-cli -p $PORT hmset "map2:katakana" "he" "ヘ"
redis-cli -p $PORT hmset "map2:katakana" "ho" "ホ"

redis-cli -p $PORT hmset "map2:katakana" "ma" "マ"
redis-cli -p $PORT hmset "map2:katakana" "mi" "ミ"
redis-cli -p $PORT hmset "map2:katakana" "mu" "ム"
redis-cli -p $PORT hmset "map2:katakana" "me" "メ"
redis-cli -p $PORT hmset "map2:katakana" "mo" "モ"

redis-cli -p $PORT hmset "map2:katakana" "ya" "ヤ"
redis-cli -p $PORT hmset "map2:katakana" "yu" "ユ"
redis-cli -p $PORT hmset "map2:katakana" "yo" "ヨ"

redis-cli -p $PORT hmset "map2:katakana" "ra" "ラ"
redis-cli -p $PORT hmset "map2:katakana" "ri" "リ"
redis-cli -p $PORT hmset "map2:katakana" "ru" "ル"
redis-cli -p $PORT hmset "map2:katakana" "re" "レ"
redis-cli -p $PORT hmset "map2:katakana" "ro" "ロ"

redis-cli -p $PORT hmset "map2:katakana" "wa" "ワ"
redis-cli -p $PORT hmset "map2:katakana" "wo" "ヲ"
redis-cli -p $PORT hmset "map2:katakana" "n" "ン"

redis-cli -p $PORT hmset "map2:katakana" "ga" "ガ"
redis-cli -p $PORT hmset "map2:katakana" "gi" "ギ"
redis-cli -p $PORT hmset "map2:katakana" "gu" "グ"
redis-cli -p $PORT hmset "map2:katakana" "ge" "ゲ"
redis-cli -p $PORT hmset "map2:katakana" "go" "ゴ"

redis-cli -p $PORT hmset "map2:katakana" "za" "ザ"
redis-cli -p $PORT hmset "map2:katakana" "zi" "ジ"
redis-cli -p $PORT hmset "map2:katakana" "zu" "ズ"
redis-cli -p $PORT hmset "map2:katakana" "ze" "ゼ"
redis-cli -p $PORT hmset "map2:katakana" "zo" "ゾ"

redis-cli -p $PORT hmset "map2:katakana" "da" "ダ"
redis-cli -p $PORT hmset "map2:katakana" "de" "デ"
redis-cli -p $PORT hmset "map2:katakana" "do" "ド"

redis-cli -p $PORT hmset "map2:katakana" "ba" "バ"
redis-cli -p $PORT hmset "map2:katakana" "bi" "ビ"
redis-cli -p $PORT hmset "map2:katakana" "bu" "ブ"
redis-cli -p $PORT hmset "map2:katakana" "be" "ベ"
redis-cli -p $PORT hmset "map2:katakana" "bo" "ボ"

redis-cli -p $PORT hmset "map2:katakana" "pa" "パ"
redis-cli -p $PORT hmset "map2:katakana" "pi" "ピ"
redis-cli -p $PORT hmset "map2:katakana" "pu" "プ"
redis-cli -p $PORT hmset "map2:katakana" "pe" "ペ"
redis-cli -p $PORT hmset "map2:katakana" "po" "ポ"

redis-cli -p $PORT hmset "map2:katakana" "kya" "キャ"
redis-cli -p $PORT hmset "map2:katakana" "kyu" "キュ"
redis-cli -p $PORT hmset "map2:katakana" "kyo" "キョ"
redis-cli -p $PORT hmset "map2:katakana" "sya" "シャ"
redis-cli -p $PORT hmset "map2:katakana" "syu" "シュ"
redis-cli -p $PORT hmset "map2:katakana" "syo" "ショ"
redis-cli -p $PORT hmset "map2:katakana" "tya" "チャ"
redis-cli -p $PORT hmset "map2:katakana" "tyu" "チュ"
redis-cli -p $PORT hmset "map2:katakana" "tyo" "チョ"
redis-cli -p $PORT hmset "map2:katakana" "nya" "ニャ"
redis-cli -p $PORT hmset "map2:katakana" "nyu" "ニュ"
redis-cli -p $PORT hmset "map2:katakana" "nyo" "ニョ"
redis-cli -p $PORT hmset "map2:katakana" "hya" "ヒャ"
redis-cli -p $PORT hmset "map2:katakana" "hyu" "ヒュ"
redis-cli -p $PORT hmset "map2:katakana" "hyo" "ヒョ"
redis-cli -p $PORT hmset "map2:katakana" "mya" "ミャ"
redis-cli -p $PORT hmset "map2:katakana" "myu" "ミュ"
redis-cli -p $PORT hmset "map2:katakana" "myo" "ミョ"
redis-cli -p $PORT hmset "map2:katakana" "rya" "リャ"
redis-cli -p $PORT hmset "map2:katakana" "ryu" "リュ"
redis-cli -p $PORT hmset "map2:katakana" "ryo" "リョ"
redis-cli -p $PORT hmset "map2:katakana" "gya" "ギャ"
redis-cli -p $PORT hmset "map2:katakana" "gyu" "ギュ"
redis-cli -p $PORT hmset "map2:katakana" "gyo" "ギョ"
redis-cli -p $PORT hmset "map2:katakana" "zya" "ジャ"
redis-cli -p $PORT hmset "map2:katakana" "zyu" "ジュ"
redis-cli -p $PORT hmset "map2:katakana" "zyo" "ジョ"
redis-cli -p $PORT hmset "map2:katakana" "bya" "ビャ"
redis-cli -p $PORT hmset "map2:katakana" "byu" "ビュ"
redis-cli -p $PORT hmset "map2:katakana" "byo" "ビョ"
redis-cli -p $PORT hmset "map2:katakana" "pya" "ピャ"
redis-cli -p $PORT hmset "map2:katakana" "pyu" "ピュ"
redis-cli -p $PORT hmset "map2:katakana" "pyo" "ピョ"
